application: udacityblog
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /addblog
  script: main.app

- url: /templatetest
  script: templus.app

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest